#torch.nn Module 사용해서 Linear Regression 구현하기

cost 함수와 hypothesis를 직접 정의할 필요가 없다

In [22]:
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(1)

In [2]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
#y=2x를 학습하기를 원함

In [4]:
#hypothesis 정의하는 방법
linear_regression_model = nn.Linear(1,1)
#인자에는 input과 output의 차원을 입력해야 한다. model에 이미 W와 b가 정의되어있다.

In [6]:
print(list(linear_regression_model.parameters()))
#W와 b를 직접 초기화하지 않아도 이미 model 내부에서 random으로 초기화하였

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [8]:
#optimizer 정의.
optimizer = torch.optim.SGD(linear_regression_model.parameters(), lr=0.01)

In [9]:
epochs = 2000
for e in range(epochs+1):
  prediction = linear_regression_model(x_train) #model을 사용할 때는 input만 넣으면 된다.

  #cost 계산
  cost = F.mse_loss(prediction, y_train)

  #0으로 gradient 초기화
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if e%100==0:
     print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          e, epochs, cost.item()
      ))



Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


#test data에 대해 적용해보자

In [23]:
x_test = torch.FloatTensor([[4.0]])
pred_y = linear_regression_model(x_test)
print("Test Data가 4일 때", pred_y)

Test Data가 4일 때 tensor([[7.9989]], grad_fn=<AddmmBackward0>)


y=2x에 4를 넣은 8과 predict 값이 차이가 존재하지 않음
W와 b가 적절하게 초기화 되었다고 볼 수 있다.

In [24]:
print(list(linear_regression_model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


#다중 선형 회귀도 구현해보자

In [25]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])
#3차원의 input에 대해서 1차원인 y값을 구하기

In [26]:
model = nn.Linear(3,1)
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [27]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)
epochs = 2000
for e in range(epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if e % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          e, epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769


In [28]:
x_test =  torch.FloatTensor([[73, 80, 75]])
pred_y = model(x_test)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.2305]], grad_fn=<AddmmBackward0>)


In [29]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]
