#선형회귀
데이터에 가장 fit한 y=wx+b를 찾는 것.
즉, 최적의 w와 b를 찾는 것이다.

In [17]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

#manual_seed() 하는 이유
다른 컴퓨터에서도 random seed를 고정시킨다.
이로 인해 동일한 값이 나온

In [18]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [19]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [20]:
W = torch.zeros(1,requires_grad=True)
#크기가 1인 tensor. 값은 0
#requires_grad=True -> 학습을 통해 계속 변하는 값임을 명시하는 방법
print(W)

tensor([0.], requires_grad=True)


In [21]:
b = torch.zeros(1,requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


현재는 y=0*x+0 이다.

#가설 세우기
코드상으로 직선의 방정식에 해당하는 가설을 선언한다. 가설의 형태를 정의한다.

In [22]:
hypo = x_train*W + b
print(hypo)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


#비용 함수 Cost Function 선언하기
여기서는 Mean Squared Error을 사용

In [23]:
cost = torch.mean((hypo - y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


#최적화 방법 정의
경사 하강법을 사용하고자 한다

In [24]:
optimizer = optim.SGD([W,b], lr=0.01)
#학습 대상 W,b를 설정하고 SGD를 사용하고 learning rate를 0.01로 설정하였다

In [25]:
#optimizer의 초기 미분값을 0으로 설정해야 한다. 이렇게 초기값을 설정해야 다음 기울기를 구할 수 있다
optimizer.zero_grad()

#비용 함수를 미분하여 gradient 계산
cost.backward()
#requires_grad=True가 설정된 모든 값을 업데이트할 때 필요한 미분값을 계산한다.

#W와 b를 실제로 업데이트
optimizer.step()

In [26]:
epochs = 1999
for e in range(epochs+1):

  hypo = x_train*W+b
  cost = torch.mean((hypo-y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if e%100 ==0:
    print("Epoch {:4d}/{} W:{:.3f}, b:{:.3f} Cost: {:.6f}".format(e, epochs, W.item(), b.item(), cost.item()))

Epoch    0/1999 W:0.353, b:0.151 Cost: 14.770963
Epoch  100/1999 W:1.746, b:0.577 Cost: 0.047939
Epoch  200/1999 W:1.801, b:0.453 Cost: 0.029624
Epoch  300/1999 W:1.843, b:0.356 Cost: 0.018306
Epoch  400/1999 W:1.877, b:0.280 Cost: 0.011312
Epoch  500/1999 W:1.903, b:0.220 Cost: 0.006990
Epoch  600/1999 W:1.924, b:0.173 Cost: 0.004319
Epoch  700/1999 W:1.940, b:0.136 Cost: 0.002669
Epoch  800/1999 W:1.953, b:0.107 Cost: 0.001649
Epoch  900/1999 W:1.963, b:0.084 Cost: 0.001019
Epoch 1000/1999 W:1.971, b:0.066 Cost: 0.000630
Epoch 1100/1999 W:1.977, b:0.052 Cost: 0.000389
Epoch 1200/1999 W:1.982, b:0.041 Cost: 0.000240
Epoch 1300/1999 W:1.986, b:0.032 Cost: 0.000149
Epoch 1400/1999 W:1.989, b:0.025 Cost: 0.000092
Epoch 1500/1999 W:1.991, b:0.020 Cost: 0.000057
Epoch 1600/1999 W:1.993, b:0.016 Cost: 0.000035
Epoch 1700/1999 W:1.995, b:0.012 Cost: 0.000022
Epoch 1800/1999 W:1.996, b:0.010 Cost: 0.000013
Epoch 1900/1999 W:1.997, b:0.008 Cost: 0.000008


#optimizer.zero_grad()를 해야하는 이유
파이토치는 미분을 통해 얻은 기울기를 이전에 계산된 기울기 값에 누적시킨다.

In [27]:
w = torch.tensor(2.0, requires_grad=True)

epochs = 20
for e in range(epochs+1):
  z=2*w

  z.backward()
  print("수삭을 w로 미분한 값 : {}".format(w.grad))

  #원래대로라면 2가 계속 나와야 하는데 2가 계속 더해져서 나온다.

수삭을 w로 미분한 값 : 2.0
수삭을 w로 미분한 값 : 4.0
수삭을 w로 미분한 값 : 6.0
수삭을 w로 미분한 값 : 8.0
수삭을 w로 미분한 값 : 10.0
수삭을 w로 미분한 값 : 12.0
수삭을 w로 미분한 값 : 14.0
수삭을 w로 미분한 값 : 16.0
수삭을 w로 미분한 값 : 18.0
수삭을 w로 미분한 값 : 20.0
수삭을 w로 미분한 값 : 22.0
수삭을 w로 미분한 값 : 24.0
수삭을 w로 미분한 값 : 26.0
수삭을 w로 미분한 값 : 28.0
수삭을 w로 미분한 값 : 30.0
수삭을 w로 미분한 값 : 32.0
수삭을 w로 미분한 값 : 34.0
수삭을 w로 미분한 값 : 36.0
수삭을 w로 미분한 값 : 38.0
수삭을 w로 미분한 값 : 40.0
수삭을 w로 미분한 값 : 42.0
