In [1]:
import numpy as np

numpy로 텐서를 만드는 방법은 [숫자, 숫자, 숫자]의 형식에서 np.array에 대입하면 된다.

In [2]:
t = [0,1,2,3,4,5,6]
t = np.array(t)
print(t)

[0 1 2 3 4 5 6]


In [3]:
print("Rank, 차원 수: ", t.ndim)
print("Shape, 전체 크기: ", t.shape)

Rank, 차원 수:  1
Shape, 전체 크기:  (7,)


여기서 (7, )의 의미는 1x7 이다.

In [4]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [5]:
print('Rank  of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank  of t:  2
Shape of t:  (4, 3)


파이토치는 numpy와 유사하지만 더 낫다

In [6]:
import torch

In [7]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)


tensor([0., 1., 2., 3., 4., 5., 6.])


In [8]:
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


In [9]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


슬라이싱은 numpy와 동일하다

In [11]:
print(t[:, 1]) #첫 번째 차원은 전체 선택하고 두 번째 차원에 대해서는 index=1인 것만 고른다.
print(t[:,1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


브로드캐스팅: 자동으로 크기를 맞춰서 연산을 수행하게 해주는 기능. row, column 수 등이 다르면 큰 쪽으로 동일하게 만든다.

In [12]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1+m2)

tensor([[4., 5.]])


행렬을 인자로 곱셈하는 것:
행렬 곱셈: matmul()
vs 행렬 원소별 곱셈: .mul()

In [15]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1],[2]])
print("Size of m1: ", m1.size())
print("Size of m2: ", m2.size())
print("Matrix multiplication")
print(m1.matmul(m2)) #2x2 * 2x1 = 2*1

Size of m1:  torch.Size([2, 2])
Size of m2:  torch.Size([2, 1])
Matrix multiplication
tensor([[ 5.],
        [11.]])


In [14]:
print("원소별 곱셈, 크기가 다르면 브로드캐스팅이 적용된다")
print(m1.mul(m2))

원소별 곱셈, 크기가 다르면 브로드캐스팅이 적용된다
tensor([[1., 2.],
        [6., 8.]])


In [ ]:
# [1]
# [2]
# ==> [[1, 1],
#      [2, 2]]

평균도 구할 수 있다

In [16]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [17]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [18]:
print("전체 평균", t.mean())

전체 평균 tensor(2.5000)


In [20]:
#평균을 이용해 차원을 줄이는 방법: dim 파라미터를 적용하면 된다.
#행을 없애는 방법
print(t.mean(dim=0))
#열을 없애는 방법
print(t.mean(dim=1))

tensor([2., 3.])
tensor([1.5000, 3.5000])


print(t.mean(dim=0))의 경우, 행을 없애므로, 2*2가 1*2가 된다. 1와 3의 평균이 첫번째 column, 2와 4의 평균이 두 번째 column으로 들어가면서 차원 축소가 된다.
print(t.mean(dim=1))의 경우에는 2*2가 2*1이 된다. 1와 2의 평균이 first row, 3와 4의 평균이 second row로 들어간다.

In [21]:
#덧셈도 할 수 있으며 차원 축소도 동일하게 할 수 있다.
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


최대값, 최대값의 위치: .max(), .argmax()

In [22]:
print(t.max()) # Returns one value: max

tensor(4.)


In [23]:
print(t.max(dim=0)) # Returns two values: max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [25]:
print(t.max(dim=0)[0])

tensor([3., 4.])


In [26]:
print(t.max(dim=0)[1])

tensor([1, 1])


In [ ]:
# [1, 1]가 무슨 의미인지 봅시다. 기존 행렬을 다시 상기해봅시다.
[[1, 2],
 [3, 4]]
# 첫번째 열에서 0번 인덱스는 1, 1번 인덱스는 3입니다.
# 두번째 열에서 0번 인덱스는 2, 1번 인덱스는 4입니다.
# 다시 말해 3과 4의 인덱스는 [1, 1]입니다.

#뷰: 원소의 수를 유지하면서 텐서의 크기 변경
.reshape()의 역할을 한다.

In [28]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
#3차원 tensor

In [29]:
print(ft.size())
#batch size * batch 하나당 row 수 * column 수

torch.Size([2, 2, 3])


In [30]:
#3차원에서 2차원으로 변경하는 방법
print(ft.view([-1,3])) #-> 텐서를 (?, 3)의 크기로 바꾼다. 즉 2차원이면서 열의 수가 3개인 것으로 바꾼다.
print(ft.view([-1,3]).size())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


view는 원소의 개수가 유지되며, view의 param으로 -1이 들어간다면, 다른 차원의 수로 -1을 대체한다.

In [31]:
#3차원에서 3차원으로
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).size())

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


#스퀴즈
1인 차원을 제거한다. -> 차원을 감소시킨다.

In [32]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [33]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


#unsqueeze
1인 차원을 추가한다. -> 차원을 증가시킨다.


In [34]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [36]:
#1*3으로 만들기
print(ft.unsqueeze(0).shape) #-> unsqueeze의 인자는 차원의 인덱스
#0을 넣으면 행에 1을 넣어준다.

torch.Size([1, 3])


In [37]:
#3*1으로 만들기
print(ft.unsqueeze(1).shape)

torch.Size([3, 1])


In [ ]:
#.view(-1,1) 또는 #view(1,-1)와 동일하다

#타입 캐스팅
텐서에는 자료형이라는 것이 있습니다. 각 데이터형별로 정의되어져 있는데, 예를 들어 32비트의 부동 소수점은 torch.FloatTensor를, 64비트의 부호 있는 정수는 torch.LongTensor를 사용합니다. GPU 연산을 위한 자료형도 있습니다. 예를 들어 torch.cuda.FloatTensor가 그 예입니다.

이런 자료형을 변형하는 것을 타입 캐스팅이라고 한다.

In [38]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [39]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [40]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


#텐서 연결하기

In [44]:
#2x2 크기 두개를 연결해보자
x= torch.FloatTensor([[1,2], [3,4]])
y= torch.FloatTensor([[5,6], [7,8]])

torch.cat([x,y], dim=0)을 통해 concatenate한다.

여기서 x,y는 합칠 Tensor, dim은 어떤 차원의 크기를 키울 것인지 정하는 인자이다.

In [46]:
print(torch.cat([x,y], dim=0))
#행이 증가하는 방향으로 합쳐졌다. 4x2가 되었다.

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [47]:
print(torch.cat([x,y], dim=1))
#열이 증가하는 방향이 되었다. 2x4가 되었다.

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


#Stacking
tensor를 쌓는 방법. .cat()과 동일하다.


In [49]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
stacked = torch.stack([x, y, z])
print(stacked)
print(stacked.shape)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
torch.Size([3, 2])


torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)을 한 것과 동일하다.

In [50]:
#dim 인자로 stack 방향을 다르게 할 수 있다.
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


#zeros_like(T), ones_like(T)
T tensor와 동일한 크기로 0 또는 1을 채우는 역할을 한다.


#덮어쓰기, tensor 연산을 기존 tensor에 반영하기

In [51]:
x = torch.FloatTensor([[1, 2], [3, 4]])
#여기서 각 요소에 2를 곱한 결과를 알고 싶을 때
print(x.mul(2))
#하지만 다시 x를 print하면 결과가 반영되지 않았다.
print(x)
#따라서 이 연산을 반영하고 싶다면 덮어쓰기를 하면 된다. 이는 연산명 뒤에 _를 붙이면 된다.
x.mul_(2)
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
