데이터를 적절하게 분리하여 train set, validation set, test set으로 나누어야 한다.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

zip 함수: 동일한 개수를 가지는 sequence 자료형에서 각 순서에 등장하는 원소들끼리 묶어준다. 즉, 두 sequence가 존재한다면, index가 같은 것들끼리 하나의 데이터로 만드는 것이다. 리스트의 리스트 구성에서 zip를 통해 x와 y를 분리하는데 사용할 수 있다.

In [ ]:
#x,y를 분리하는데 사용
x,y = zip(['a', 1], ['b', 2], ['c', 3])
print("x 데이터 : ", x)
print("y 데이터 : ", y)


x 데이터 :  ('a', 'b', 'c')
y 데이터 :  (1, 2, 3)


In [ ]:
sequences = [['a', '1'], ['b','2'],['c',3]]
x,y = zip(*sequences)
print("x 데이터 : ", x)
print("y 데이터 : ", y)


x 데이터 :  ('a', 'b', 'c')
y 데이터 :  ('1', '2', 3)


데이터프레임에서는 열 이름으로 접근하여 분리할 수 있다.

In [ ]:
values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']
df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [ ]:
x = df['메일 본문']
y=df['스팸 메일 유무']
print("x 데이터 : ", x)
print("y 데이터 : ", y)

x 데이터 :  0          당신에게 드리는 마지막 혜택!
1      내일 뵐 수 있을지 확인 부탁드...
2      도연씨. 잘 지내시죠? 오랜만입...
3    (광고) AI로 주가를 예측할 수 있다!
Name: 메일 본문, dtype: object
y 데이터 :  0    1
1    0
2    0
3    1
Name: 스팸 메일 유무, dtype: int64


numpy array에서는 슬라이싱을 통해 분리한다.

In [ ]:
np_array = np.arange(0,16).reshape((4,4))
print('전체 데이터 :')
print(np_array)

전체 데이터 :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
x = np_array[:, :3]
y = np_array[:,3]

print('X 데이터 :')
print(X)
print('y 데이터 :',y)

X 데이터 :
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
y 데이터 : [ 3  7 11 15]


사이킷런은 train set와 test set을 분리하는 함수를 지원해준다.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=1234)
X는 배열이나 데이터프레임 형태로 독립 변수 데이터이다.
Y도 배열이나 데이터프레임 형태이고 종속 변수 데이터이다.
train_size, test_size 각각 test set 개수, train set 개수를 나타낸다.

In [12]:
x, y = np.arange(10).reshape((5, 2)), np.arange(5)

print('x 전체 데이터 :')
print(x)
print('y 전체 데이터 :')
print(y)

x 전체 데이터 :
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
y 전체 데이터 :
[0 1 2 3 4]


In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=12)

In [14]:
print("X train")
print(x_train)
print("X test")
print(x_test)

X train
[[4 5]
 [8 9]
 [6 7]]
X test
[[0 1]
 [2 3]]


In [15]:
print('y 훈련 데이터 :')
print(y_train)
print('y 테스트 데이터 :')
print(y_test)

y 훈련 데이터 :
[2 4 3]
y 테스트 데이터 :
[0 1]
